[package]
name = "os"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "os"
test = true
bench = false

[features]
default = ["bootimage"]
bootimage = []

[package.metadata.bootimage]
test-args = [
    "-device", "isa-debug-exit,iobase=0xf4,iosize=0x04", 
    "-serial", "stdio",
    "-display", "none",
    "--device", "rtl8139"
]
run-args = [
    "-s", # open gdb server for debugging on localhost:1234
    "-serial", "stdio",
    "-device", "rtl8139,netdev=net0",
    # "-netdev", "bridge,br=br0,id=net0,helper=/run/wrappers/bin/qemu-bridge-helper", # allows vm to act in local network
    "-netdev", "tap,id=net0,ifname=tap0,script=no,downscript=no",
    "-object", "filter-dump,id=f1,netdev=net0,file=dump.dat"
]
test-success-exit-code = 33
test-timeout = 300 #seconds

# [lib]
# name = "os"
# crate-type = ["rlib", "staticlib"]
# test = false

# [[test]]
# name = "should_panic"
# harness = false
# default-features = false
#
# [[test]]
# name = "stack_overflow"
# harness = false

[dependencies]
bootloader = { version = "0.9", features = ["map_physical_memory"] }
x86_64 = "0.15.4"
pc-keyboard = "0.8.0"
linked_list_allocator = "0.9.0"
bitflags = "2.11.1"
hashbrown = "0.17.1"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[dependencies.crossbeam-queue]
version = "0.3.11"
default-features = false
features = ["alloc"]

[dependencies.conquer-once]
version = "0.2.0"
default-features = false

[dependencies.futures-util]
version = "0.3.4"
default-features = false
features = ["alloc"]


[dev-dependencies]
os = { path = ".", default-features = false }
