[package]
name = "os"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "os"
test = true
bench = false

[features]
default = ["bootimage"]
bootimage = []

[package.metadata.bootimage]
test-args = [
    "-device", "isa-debug-exit,iobase=0xf4,iosize=0x04", 
    "-serial", "stdio",
    "-display", "none",
    "--device", "rtl8139"
]
run-args = ["-serial", "stdio", "--device", "rtl8139"]
test-success-exit-code = 33
test-timeout = 300 #seconds

# [lib]
# name = "os"
# crate-type = ["rlib", "staticlib"]
# test = false

# [[test]]
# name = "should_panic"
# harness = false
# default-features = false
#
# [[test]]
# name = "stack_overflow"
# harness = false

[dependencies]
bootloader = { version = "0.9", features = ["map_physical_memory"] }
x86_64 = "0.15.4"
pc-keyboard = "0.8.0"
linked_list_allocator = "0.9.0"
bitflags = "2.11.1"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[dependencies.crossbeam-queue]
version = "0.3.11"
default-features = false
features = ["alloc"]

[dependencies.conquer-once]
version = "0.2.0"
default-features = false

[dependencies.futures-util]
version = "0.3.4"
default-features = false
features = ["alloc"]


[dev-dependencies]
os = { path = ".", default-features = false }
